alias ..='cd ..'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias apache='sudo /etc/init.d/apache2'
alias build='time (node ~/main/build/r.js -o ~/main/build/require.build.hosting.js ; node ~/main/build/r.js -o ~/main/build/require.build.dhm.js ; clearcache ; dump)'
alias clear='clear; printf '\''%*s\n'\'' 238 '\'''\'' | tr '\'' '\'' \#'
alias cls='clear'
alias fullpath='readlink -f '
alias godb='mysql -uroot -proot --prompt="Tirate un query: "'
alias gow='cd /home/jonas/www/'
alias gre='grep --exclude-dir=".svn" --color=auto'
alias grep='gre -n'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias on='/opt/netbeans-8.0/bin/netbeans --open'
alias py='python'
alias query='godb -e'
alias restart='sudo /etc/init.d/apache2 restart'
alias run='python ~/django/classijango/src/manage.py runserver 127.0.0.1:8000'
alias t='trans'
alias trans='bash ~/translate.sh '
alias zorro1='rdesktop 127.0.0.1 -g 1600x900 -u"User" -p"Password" -k es -a 16 -r disk:share=~/Desktop/Shared -r clipboard:CLIPBOARD'
